server {
    listen 80;
    server_name _;
    
    # Pasta onde os arquivos do React buildado vão ficar
    root /usr/share/nginx/html;
    index index.html;

    # A mágica acontece aqui
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Cache para deixar o site mais rápido
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}